// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN5V4VP9gPSobTm78UDX65Ldrd6ewbkdE',
    appId: '1:532851780061:web:fc275c0434038677872e34',
    messagingSenderId: '532851780061',
    projectId: 'medical-appointment-app-md2',
    authDomain: 'medical-appointment-app-md2.firebaseapp.com',
    storageBucket: 'medical-appointment-app-md2.firebasestorage.app',
    measurementId: 'G-0B6RKEDPE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PRyTqwKbA3ZUm92gQZ60a4jbkttv35E',
    appId: '1:532851780061:android:941829e5bcec1ba1872e34',
    messagingSenderId: '532851780061',
    projectId: 'medical-appointment-app-md2',
    storageBucket: 'medical-appointment-app-md2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD32kpNH6STLMaNERcOq0mcE6b6It1V-O8',
    appId: '1:532851780061:ios:236c2f2d21c7ec8e872e34',
    messagingSenderId: '532851780061',
    projectId: 'medical-appointment-app-md2',
    storageBucket: 'medical-appointment-app-md2.firebasestorage.app',
    iosBundleId: 'com.example.medicalAppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD32kpNH6STLMaNERcOq0mcE6b6It1V-O8',
    appId: '1:532851780061:ios:236c2f2d21c7ec8e872e34',
    messagingSenderId: '532851780061',
    projectId: 'medical-appointment-app-md2',
    storageBucket: 'medical-appointment-app-md2.firebasestorage.app',
    iosBundleId: 'com.example.medicalAppointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN5V4VP9gPSobTm78UDX65Ldrd6ewbkdE',
    appId: '1:532851780061:web:80660005cdddb8aa872e34',
    messagingSenderId: '532851780061',
    projectId: 'medical-appointment-app-md2',
    authDomain: 'medical-appointment-app-md2.firebaseapp.com',
    storageBucket: 'medical-appointment-app-md2.firebasestorage.app',
    measurementId: 'G-N91FZ33CP5',
  );
}
